services:
  web:
    image: ghcr.io/mupinnn/cakyu-helper/web:${IMAGE_TAG}
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        VITE_API_URL: ""
    depends_on:
      - api
    restart: unless-stopped

  api:
    image: ghcr.io/mupinnn/cakyu-helper/api:${IMAGE_TAG}
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: unless-stopped
