export const choices = {
  classType: ["Reguler", "Profesional"],
  classProgram: [
    "Online / Daring / Di tempat domisisli",
    "Offline / Luring / Di Kampus Cakrawala University",
  ],
  intakeYear: ["2024", "2025"],
  intakeMonth: ["Maret", "September"],
  ongoingSemester: ["I (Ganjil)", "II (Genap)", "III (Ganjil)", "IV (Genap)"],
  faculty: ["Ilmu Komputer", "Ekonomi dan Bisnis"],
  studyProgram: [
    "Bisnis Digital",
    "Ekonomi Keuangan dan Perbankan",
    "Sains Data",
    "Ilmu Komputer",
    "Sistem dan Teknologi Informasi",
  ],
  subject: [
    "CIK1107 - Discrete Mathematics",
    "CIK1109 - Human-Computer Interaction",
    "CIK2108 - Object-Oriented Programming",
    "CIK2109 - Data Structures",
    "CIK4101 - Data Warehousing and Mining",
    "IKR2125 - Database Systems",
    "IKR2130 - Human-Centered Design",
    "IKR2131 - Programming Fundamentals (Python)",
    "IKR2148 - Graphics and Interactive Techniques",
    "PSD1209 - Text Mining",
    "SDA2133 - Database Systems",
    "SDA2138 - Data Wrangling",
    "SDA2141 - Foundations of Data Science",
    "STI2131 - Database I: Data Modelling and Query Languages",
    "STI2136 - Business & Technology Modelling",
    "STI2138 - Programming for Business",
    "STI2155 - Visualization",
    "WUC1113 - Design Thinking",
    "WUC1115 - Technical/Professional Writing",
    "BDL2108 - E-Commerce",
    "BDL2144 - Basics of User Interface Design & User Experience (UI/UX)",
    "BDL2146 - Consumer Behavior",
    "BDL2148 - Basic Web Development",
    "BDL2157 - Introduction to Data Analytics",
    "CEB1102 - Introduction to Economics",
    "CEB1103 - Financial Management",
    "CEB1104 - Introduction to Accounting",
    "CEB1105 - Financial Markets and FinTech",
    "CEB2101 - Business Communication and Negotiation",
    "EKP2145 - Business and Economic Mathematics",
    "EKP2150 - Banking and Non-Bank Financial Institutions",
    "EKP2152 - Microeconomics",
    "EKP2153 - Financial Accounting",
    "EKP2154 - Financial Management",
    "EKP2162 - Algorithmic Trading",
    "EKP2169 - Portfolio Theory and Investment Management",
    "EKP2170 - Auditing II",
    "WUC1114 - Technical/Professional Writing",
    "WUC1116 - English",
  ],
  classCode: [
    "BTM01",
    "BTM02",
    "DaWr1",
    "DaWr2",
    "DB01",
    "DB02",
    "DB03",
    "DB04",
    "DB05",
    "DB06",
    "DMat1",
    "DS01",
    "DS02",
    "DS03",
    "DS04",
    "DS05",
    "DS06",
    "Dtwm1",
    "Dtwm2",
    "Dtwm3",
    "Dtwm4",
    "FoDS1",
    "GrIT1",
    "GrIT2",
    "HCD01",
    "HCD02",
    "HCI01",
    "OOP1",
    "OOP2",
    "OOP3",
    "OOP4",
    "OOP5",
    "OOP6",
    "Prog1",
    "Prog2",
    "Tnkg1",
    "TPW01",
    "TPW02",
    "TPW03",
    "TPW04",
    "TxMg1",
    "TxMg2",
    "Vis01",
    "Vis02",
    "Aud01",
    "Aud02",
    "Bank1",
    "Bank2",
    "BEM1",
    "BEM2",
    "BuCn1",
    "BuCn2",
    "BuCn3",
    "BuCn4",
    "BuCn5",
    "BuCn6",
    "BWD01",
    "BWD02",
    "BWD03",
    "BWD04",
    "BWD05",
    "BWD06",
    "CBh06",
    "Ecom1",
    "Ecom2",
    "Ecom3",
    "Ecom4",
    "Ecom5",
    "Ecom6",
    "Eng1",
    "Eng2",
    "Eng3",
    "Eng4",
    "Eng5",
    "FAcc1",
    "FAcc2",
    "FMgt1",
    "FMgt2",
    "FMgt3",
    "FMgt4",
    "FnMg1",
    "FTec1",
    "IAcc1",
    "IEco1",
    "InDA0",
    "InDA6",
    "InDA7",
    "InDA8",
    "InDA9",
    "MicE1",
    "MicE2",
    "Port1",
    "Port2",
    "TPW05",
    "TPW06",
    "TPW07",
    "TPW08",
    "Trad1",
    "UIUX1",
    "UIUX2",
    "UIUX3",
    "UIUX4",
    "UIUX5",
  ],
  lecturer: [
    "Adam Ginza Amanda Malik",
    "Adam Puspabhuana, M.Kom",
    "Afrin Dwimeyriana",
    "Agistya Maharani Joner",
    "Ahya Radiatul Kamila",
    "Aisyah Humaerah, S.E, MBA",
    "Akhsanu Amalia Putri, , S.Psi., MSc.",
    "Amsal Maestro, S.Kom., M.Kom.",
    "Cantika Nur Previana",
    "Christoper Joshua",
    "Ciptoning Hestomo, S.Kom, MTI",
    "Dimas Ananda, S.Stat., M.T.I.",
    "Dr. Fandy Neta, S.Pd., M.Pd.T",
    "Dr. Lina Nurjanah, , S.P., M.B.A.",
    "Drestanto Muhammad Dyasputro, , ST, MCS",
    "Dwi Andika Irawan",
    "Dwi Winarno, MBA",
    "Elvira Masitoh Purbaningrum, S.E., M.B.A.",
    "Fennicia Auliantika Rossianti, S.E., M.M., CFP",
    "Ferdian Aditya Pratama",
    "Findy Findy Idoliany, , S.Mn., M.M.",
    "Gilang Bagaskara, S.E., MBA.",
    "Hamzah Ramadhan, , M.A.",
    "Hedy Pamungkas, S.T., M.T.I",
    "Hendi Yudhanto Adinugroho, M.M",
    "Herwinto Ch Sutantyo, , M.A., M.B.A",
    "Irham Fathurrahman, SE, MS",
    "Jelita Lanmora Lubis, S.E. M.M",
    "Lawrence Adi Supriyono, S.Kom, M.T.",
    "Lufty Abdillah, S.Kom., M.M.S.I.",
    "Mahira Falevy, , S.T, M. IDEA",
    "Maulana Hamidy Chash Chash Al Haque, , S.T., M.Cs., M.Sc.",
    "Michael Wijaya Saputra, S.Kom, M.Sc",
    "Miftah Faridh Nasir, S.E., Ak., M.Si., CSA., CRP.",
    "Ms. Sabila Nurwardani, S.Kom., M.T.I",
    "Muhamad Rifky Adhani",
    "Nabila Azzah Shafy Arkabintaan",
    "Nadhira Azzah Shafy Arkabintaan, , S.E., B.Sc., M.Sc.",
    "Nenggala Yudhabrama, S.T., MSc.",
    "Nico",
    "Nurul Diena Novania, , ST, MT",
    "Rangga Satya Pratama",
    "Ridwan Idham, S.Si., M.M.",
    "Rozan Hanifan, S.Si., MSM",
    "Suhendin, MM",
    "Teofebano Kristo, S.T. MSc",
    "Veny Anggraini, S.Si., M.T.I.",
    "Wahyu Amaldi, M.Kom",
    "Wahyu Mulyadi, S.AB.,M.Si",
    "Yudi Triyana, S.T., MMsib., CEH.,CSA., CySA.",
  ],
  session: [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8 (Ujian Tengah Semester)",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16 (Ujian Akhir Semester)",
  ],
  levelOfUnderstanding: [
    "(1) Saya tidak memahami sedikitpun materi dari kelas hari ini (0-24%)",
    "(2) Saya memahami sebagian kecil materi dari kelas hari ini (25-49%)",
    "(3) Saya hanya memahami sebagian dari kelas hari ini (50-59%)",
    "(4) Saya memahami sebagian besar dari kelas hari ini (60-79%)",
    "(5) Saya memahami seluruh materi dari kelas hari ini (80-100%)",
  ],
  classInteractivity: [
    "(1) Keberjalanan kelas tidak menarik dan membosankan (hanya penjelasan satu arah dari mentor, minim tanya jawab, tidak ada sesi praktek)",
    "(2) Keberjalanan kelas sedikit menarik, tetapi masih membosankan. (penjelasan satu arah dari mentor, terdapat beberapa kegiatan tanya jawab tapi kurang interaksi, tidak ada sesi praktik)",
    "(3) Keberjalanan kelas kurang menarik, tetapi kegiatan kelas tidak membosankan (penjelasan satu arah dari mentor, terdapat beberapa kegiatan tanya jawab, dan ada sesi praktik)",
    "(4) Keberjalanan kelas cukup menarik dan tidak membosankan. (penjelasan dua arah dari mentor, terdapat kegiatan tanya jawab, dan ada sesi praktik)",
    "(5) Keberjalanan kelas sangat menarik dan tidak membosankan sama sekali (semua aspek sangat bagus)",
  ],
  lecturerPerformance: [
    "(1) dosen kurang baik dalam menyampaikan materi dari deck/ppt sehingga saya tidak begitu memahami materi",
    "(2) dosen hanya menyampaikan materi dari deck/ppt dan tidak menciptakan suasana interaktif",
    "(3) dosen hanya menyampaikan materi dari deck, tetapi memfasilitasi diskusi & tanya jawab",
    "(4) dosen menyampaikan materi dari deck, memfasilitasi diskusi & tanya jawab, serta menciptakan suasana belajar yang menyenangkan",
    "(5) dosen dengan passionate menyampaikan materi dari deck, serta memfasilitasi diskusi & tanya jawab, sehingga suasana kelas terasa sangat hidup dan saya tidak hanya memperoleh ilmu baru, melainkan juga terinspirasi",
  ],
} as const;
