name: Weekly updates the schedules

on:
  schedule:
    - cron: "0 8 * * 0"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  setup-matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.setup-matrix.outputs.matrix }}

    steps:
      - id: setup-matrix
        run: |
          JSON_ARRAY='[{"environment":"student-ahmad-muwaffaq","intakeYear":"2025","intakeMonth":"September","ongoingSemester":"II (Genap)","studyProgram":"Sains Data","classType":"Profesional"}]'
          echo "matrix=$JSON_ARRAY" >> $GITHUB_OUTPUT

  update-schedules:
    needs: setup-matrix
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJSON(needs.setup-matrix.outputs.matrix) }}

    environment: ${{ matrix.config.environment }}

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.3

      - run: bun install

      - name: Scrape schedules
        env:
          PUPPETEER_EXECUTABLE_PATH: "/usr/bin/google-chrome"
          SIAKAD_URL: ${{ secrets.SIAKAD_URL }}
        run: |
          cd apps/cli
          bun fetch:schedules \
            --intakeYear "${{ matrix.config.intakeYear }}" \
            --intakeMonth "${{ matrix.config.intakeMonth }}" \
            --ongoingSemester "${{ matrix.config.ongoingSemester }}" \
            --studyProgram "${{ matrix.config.studyProgram }}" \
            --classType "${{ matrix.config.classType }}" \
            --siakadEmail "${{ secrets.SIAKAD_EMAIL }}" \
            --siakadPassword "${{ secrets.SIAKAD_PASSWORD }}"

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        id: cpr
        with:
          commit-message: "update schedule for ${{ matrix.config.studyProgram }} ${{ matrix.config.classType }} ${{ matrix.config.ongoingSemester }} ${{ matrix.config.intakeMonth }} ${{ matrix.config.intakeYear }}"
          title: "Automated: update schedule for ${{ matrix.config.studyProgram }} ${{ matrix.config.classType }} ${{ matrix.config.ongoingSemester }} ${{ matrix.config.intakeMonth }} ${{ matrix.config.intakeYear }}"
          body: "This PR was automatically created by a GitHub Action."
          branch: "automated-schedule-update-from-${{ matrix.config.environment }}"
          base: main

      - name: Auto-merge PR
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: gh pr merge --auto --squash "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.PAT }}
